<?php

namespace Database\Seeders;

use App\Modules\V1\Themes\Domain\Models\Theme;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [
            [
                'price' => null,
                'name'  => 'Default Light',
                'color' => '#006800',
                'colors' => json_encode([
                    "light" => [
                        "primitive" => [
                            "primary" => [
                                "50" => "#e5f0e5",
                                "100" => "#c1ddc1",
                                "200" => "#9aca9a",
                                "300" => "#70b670",
                                "400" => "#42a542",
                                "500" => "#006800",
                                "600" => "#005f00",
                                "700" => "#005300",
                                "800" => "#004700",
                                "900" => "#003400",
                            ],
                            "secondary" => [
                                "50" => "#fffdf5",
                                "100" => "#fdf1ca",
                                "200" => "#fae5a0",
                                "300" => "#f5d87b",
                                "400" => "#edcb5c",
                                "500" => "#e4be44",
                                "600" => "#d7b031",
                                "700" => "#c7a123",
                                "800" => "#b38f19",
                                "900" => "#9e7d12",
                            ],
                            "neutral" => [
                                "0" => "#ffffff",
                                "50" => "#f2f2f2",
                                "100" => "#e4e4e4",
                                "200" => "#cacaca",
                                "300" => "#afafaf",
                                "400" => "#939393",
                                "500" => "#797979",
                                "600" => "#5e5e5e",
                                "700" => "#434343",
                                "800" => "#282828",
                                "900" => "#0d0d0d",
                            ],
                            "error" => [
                                "50" => "#ffe5e5",
                                "100" => "#ffcccc",
                                "200" => "#ff9999",
                                "300" => "#ff6666",
                                "400" => "#ff3333",
                                "500" => "#ff4b4b",
                                "600" => "#cc0000",
                                "700" => "#990000",
                            ],
                            "warning" => [
                                "50" => "#fff9e5",
                                "100" => "#fff2cc",
                                "200" => "#ffe699",
                                "300" => "#ffd966",
                                "400" => "#ffcc33",
                                "500" => "#ffc107",
                                "600" => "#cc9900",
                                "700" => "#997300",
                            ],
                            "success" => [
                                "50" => "#edf7ee",
                                "100" => "#dbf0dc",
                                "200" => "#b8e0b9",
                                "300" => "#94d196",
                                "400" => "#71c173",
                                "500" => "#4caf4f",
                                "600" => "#3e8e40",
                                "700" => "#2e6b30",
                            ],
                        ],
                        "semantic" => [
                            "text" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.700}",
                                "tertiary" => "{neutral.500}",
                                "disabled" => "{neutral.400}",
                                "inverse" => "{neutral.0}",
                                "link" => "{primary.600}",
                                "linkHover" => "{primary.700}",
                            ],
                            "background" => [
                                "page" => "{neutral.50}",
                                "section" => "{neutral.100}",
                                "card" => "{neutral.0}",
                                "overlay" => "rgba(0,0,0,0.4)",
                            ],
                            "border" => [
                                "default" => "{neutral.200}",
                                "strong" => "{neutral.300}",
                                "inverse" => "{neutral.0}",
                            ],
                            "icon" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.600}",
                                "tertiary" => "{neutral.500}",
                                "inverse" => "{neutral.0}",
                                "brand" => "{primary.500}",
                            ],
                            "button" => [
                                "primary" => [
                                    "bg" => "{primary.500}",
                                    "bgHover" => "{primary.600}",
                                    "bgPressed" => "{primary.700}",
                                    "bgDisabled" => "{primary.300}",
                                    "text" => "{neutral.0}",
                                ],
                                "secondary" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{primary.50}",
                                    "bgPressed" => "{primary.100}",
                                    "text" => "{primary.600}",
                                    "textDisabled" => "{primary.300}",
                                    "border" => "{primary.500}",
                                ],
                                "ghost" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{neutral.900}",
                                ],
                            ],
                            "status" => [
                                "error" => [
                                    "main" => "{error.500}",
                                    "bg" => "{error.50}",
                                    "text" => "{error.700}",
                                ],
                                "warning" => [
                                    "main" => "{warning.500}",
                                    "bg" => "{warning.50}",
                                    "text" => "{warning.700}",
                                ],
                                "success" => [
                                    "main" => "{success.500}",
                                    "bg" => "{success.50}",
                                    "text" => "{success.700}",
                                ],
                            ],
                        ],
                    ],
                    "dark" => [
                        "primitive" => [
                            "primary" => [
                                "500" => "#42a542",
                                "600" => "#70b670",
                                "700" => "#9aca9a",
                            ],
                            "secondary" => [
                                "500" => "#e4be44",
                            ],
                            "neutral" => [
                                "0" => "#0d0d0d",
                                "50" => "#1a1a1a",
                                "100" => "#262626",
                                "200" => "#333333",
                                "300" => "#404040",
                                "400" => "#666666",
                                "500" => "#999999",
                                "600" => "#bfbfbf",
                                "700" => "#d9d9d9",
                                "800" => "#f2f2f2",
                                "900" => "#ffffff",
                            ],
                            "error" => [
                                "500" => "#ff6666",
                                "700" => "#ff9999",
                                "50" => "#330000",
                            ],
                            "warning" => [
                                "500" => "#ffd966",
                                "700" => "#ffe699",
                                "50" => "#332600",
                            ],
                            "success" => [
                                "500" => "#71c173",
                                "700" => "#94d196",
                                "50" => "#0f2410",
                            ],
                        ],
                        "semantic" => [
                            "text" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.700}",
                                "tertiary" => "{neutral.500}",
                                "disabled" => "{neutral.400}",
                                "inverse" => "{neutral.0}",
                                "link" => "{primary.600}",
                                "linkHover" => "{primary.700}",
                            ],
                            "background" => [
                                "page" => "{neutral.0}",
                                "section" => "{neutral.50}",
                                "card" => "{neutral.100}",
                                "overlay" => "rgba(0,0,0,0.6)",
                            ],
                            "border" => [
                                "default" => "{neutral.200}",
                                "strong" => "{neutral.300}",
                                "inverse" => "{neutral.0}",
                            ],
                            "icon" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.600}",
                                "tertiary" => "{neutral.500}",
                                "inverse" => "{neutral.0}",
                                "brand" => "{primary.500}",
                            ],
                            "button" => [
                                "primary" => [
                                    "bg" => "{primary.500}",
                                    "bgHover" => "{primary.600}",
                                    "bgPressed" => "{primary.700}",
                                    "bgDisabled" => "{primary.300}",
                                    "text" => "{neutral.0}",
                                ],
                                "secondary" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{primary.600}",
                                    "textDisabled" => "{primary.300}",
                                    "border" => "{primary.500}",
                                ],
                                "ghost" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{neutral.900}",
                                ],
                            ],
                            "status" => [
                                "error" => [
                                    "main" => "{error.500}",
                                    "bg" => "{error.50}",
                                    "text" => "{error.700}",
                                ],
                                "warning" => [
                                    "main" => "{warning.500}",
                                    "bg" => "{warning.50}",
                                    "text" => "{warning.700}",
                                ],
                                "success" => [
                                    "main" => "{success.500}",
                                    "bg" => "{success.50}",
                                    "text" => "{success.700}",
                                ],
                            ],
                        ],
                    ],
                ]),
            ],
            [
                'price' => null,
                'name'  => 'Default Light',
                'color' => '#006800',
                'colors' => json_encode([
                    "light" => [
                        "primitive" => [
                            "primary" => [
                                "50" => "#e5f0e5",
                                "100" => "#c1ddc1",
                                "200" => "#9aca9a",
                                "300" => "#70b670",
                                "400" => "#42a542",
                                "500" => "#006800",
                                "600" => "#005f00",
                                "700" => "#005300",
                                "800" => "#004700",
                                "900" => "#003400",
                            ],
                            "secondary" => [
                                "50" => "#fffdf5",
                                "100" => "#fdf1ca",
                                "200" => "#fae5a0",
                                "300" => "#f5d87b",
                                "400" => "#edcb5c",
                                "500" => "#e4be44",
                                "600" => "#d7b031",
                                "700" => "#c7a123",
                                "800" => "#b38f19",
                                "900" => "#9e7d12",
                            ],
                            "neutral" => [
                                "0" => "#ffffff",
                                "50" => "#f2f2f2",
                                "100" => "#e4e4e4",
                                "200" => "#cacaca",
                                "300" => "#afafaf",
                                "400" => "#939393",
                                "500" => "#797979",
                                "600" => "#5e5e5e",
                                "700" => "#434343",
                                "800" => "#282828",
                                "900" => "#0d0d0d",
                            ],
                            "error" => [
                                "50" => "#ffe5e5",
                                "100" => "#ffcccc",
                                "200" => "#ff9999",
                                "300" => "#ff6666",
                                "400" => "#ff3333",
                                "500" => "#ff4b4b",
                                "600" => "#cc0000",
                                "700" => "#990000",
                            ],
                            "warning" => [
                                "50" => "#fff9e5",
                                "100" => "#fff2cc",
                                "200" => "#ffe699",
                                "300" => "#ffd966",
                                "400" => "#ffcc33",
                                "500" => "#ffc107",
                                "600" => "#cc9900",
                                "700" => "#997300",
                            ],
                            "success" => [
                                "50" => "#edf7ee",
                                "100" => "#dbf0dc",
                                "200" => "#b8e0b9",
                                "300" => "#94d196",
                                "400" => "#71c173",
                                "500" => "#4caf4f",
                                "600" => "#3e8e40",
                                "700" => "#2e6b30",
                            ],
                        ],
                        "semantic" => [
                            "text" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.700}",
                                "tertiary" => "{neutral.500}",
                                "disabled" => "{neutral.400}",
                                "inverse" => "{neutral.0}",
                                "link" => "{primary.600}",
                                "linkHover" => "{primary.700}",
                            ],
                            "background" => [
                                "page" => "{neutral.50}",
                                "section" => "{neutral.100}",
                                "card" => "{neutral.0}",
                                "overlay" => "rgba(0,0,0,0.4)",
                            ],
                            "border" => [
                                "default" => "{neutral.200}",
                                "strong" => "{neutral.300}",
                                "inverse" => "{neutral.0}",
                            ],
                            "icon" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.600}",
                                "tertiary" => "{neutral.500}",
                                "inverse" => "{neutral.0}",
                                "brand" => "{primary.500}",
                            ],
                            "button" => [
                                "primary" => [
                                    "bg" => "{primary.500}",
                                    "bgHover" => "{primary.600}",
                                    "bgPressed" => "{primary.700}",
                                    "bgDisabled" => "{primary.300}",
                                    "text" => "{neutral.0}",
                                ],
                                "secondary" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{primary.50}",
                                    "bgPressed" => "{primary.100}",
                                    "text" => "{primary.600}",
                                    "textDisabled" => "{primary.300}",
                                    "border" => "{primary.500}",
                                ],
                                "ghost" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{neutral.900}",
                                ],
                            ],
                            "status" => [
                                "error" => [
                                    "main" => "{error.500}",
                                    "bg" => "{error.50}",
                                    "text" => "{error.700}",
                                ],
                                "warning" => [
                                    "main" => "{warning.500}",
                                    "bg" => "{warning.50}",
                                    "text" => "{warning.700}",
                                ],
                                "success" => [
                                    "main" => "{success.500}",
                                    "bg" => "{success.50}",
                                    "text" => "{success.700}",
                                ],
                            ],
                        ],
                    ],
                    "dark" => [
                        "primitive" => [
                            "primary" => [
                                "500" => "#42a542",
                                "600" => "#70b670",
                                "700" => "#9aca9a",
                            ],
                            "secondary" => [
                                "500" => "#e4be44",
                            ],
                            "neutral" => [
                                "0" => "#0d0d0d",
                                "50" => "#1a1a1a",
                                "100" => "#262626",
                                "200" => "#333333",
                                "300" => "#404040",
                                "400" => "#666666",
                                "500" => "#999999",
                                "600" => "#bfbfbf",
                                "700" => "#d9d9d9",
                                "800" => "#f2f2f2",
                                "900" => "#ffffff",
                            ],
                            "error" => [
                                "500" => "#ff6666",
                                "700" => "#ff9999",
                                "50" => "#330000",
                            ],
                            "warning" => [
                                "500" => "#ffd966",
                                "700" => "#ffe699",
                                "50" => "#332600",
                            ],
                            "success" => [
                                "500" => "#71c173",
                                "700" => "#94d196",
                                "50" => "#0f2410",
                            ],
                        ],
                        "semantic" => [
                            "text" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.700}",
                                "tertiary" => "{neutral.500}",
                                "disabled" => "{neutral.400}",
                                "inverse" => "{neutral.0}",
                                "link" => "{primary.600}",
                                "linkHover" => "{primary.700}",
                            ],
                            "background" => [
                                "page" => "{neutral.0}",
                                "section" => "{neutral.50}",
                                "card" => "{neutral.100}",
                                "overlay" => "rgba(0,0,0,0.6)",
                            ],
                            "border" => [
                                "default" => "{neutral.200}",
                                "strong" => "{neutral.300}",
                                "inverse" => "{neutral.0}",
                            ],
                            "icon" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.600}",
                                "tertiary" => "{neutral.500}",
                                "inverse" => "{neutral.0}",
                                "brand" => "{primary.500}",
                            ],
                            "button" => [
                                "primary" => [
                                    "bg" => "{primary.500}",
                                    "bgHover" => "{primary.600}",
                                    "bgPressed" => "{primary.700}",
                                    "bgDisabled" => "{primary.300}",
                                    "text" => "{neutral.0}",
                                ],
                                "secondary" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{primary.600}",
                                    "textDisabled" => "{primary.300}",
                                    "border" => "{primary.500}",
                                ],
                                "ghost" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{neutral.900}",
                                ],
                            ],
                            "status" => [
                                "error" => [
                                    "main" => "{error.500}",
                                    "bg" => "{error.50}",
                                    "text" => "{error.700}",
                                ],
                                "warning" => [
                                    "main" => "{warning.500}",
                                    "bg" => "{warning.50}",
                                    "text" => "{warning.700}",
                                ],
                                "success" => [
                                    "main" => "{success.500}",
                                    "bg" => "{success.50}",
                                    "text" => "{success.700}",
                                ],
                            ],
                        ],
                    ],
                ]),
            ],
            [
                'price' => null,
                'name'  => 'Default Light',
                'color' => '#006800',
                'colors' => json_encode([
                    "light" => [
                        "primitive" => [
                            "primary" => [
                                "50" => "#e5f0e5",
                                "100" => "#c1ddc1",
                                "200" => "#9aca9a",
                                "300" => "#70b670",
                                "400" => "#42a542",
                                "500" => "#006800",
                                "600" => "#005f00",
                                "700" => "#005300",
                                "800" => "#004700",
                                "900" => "#003400",
                            ],
                            "secondary" => [
                                "50" => "#fffdf5",
                                "100" => "#fdf1ca",
                                "200" => "#fae5a0",
                                "300" => "#f5d87b",
                                "400" => "#edcb5c",
                                "500" => "#e4be44",
                                "600" => "#d7b031",
                                "700" => "#c7a123",
                                "800" => "#b38f19",
                                "900" => "#9e7d12",
                            ],
                            "neutral" => [
                                "0" => "#ffffff",
                                "50" => "#f2f2f2",
                                "100" => "#e4e4e4",
                                "200" => "#cacaca",
                                "300" => "#afafaf",
                                "400" => "#939393",
                                "500" => "#797979",
                                "600" => "#5e5e5e",
                                "700" => "#434343",
                                "800" => "#282828",
                                "900" => "#0d0d0d",
                            ],
                            "error" => [
                                "50" => "#ffe5e5",
                                "100" => "#ffcccc",
                                "200" => "#ff9999",
                                "300" => "#ff6666",
                                "400" => "#ff3333",
                                "500" => "#ff4b4b",
                                "600" => "#cc0000",
                                "700" => "#990000",
                            ],
                            "warning" => [
                                "50" => "#fff9e5",
                                "100" => "#fff2cc",
                                "200" => "#ffe699",
                                "300" => "#ffd966",
                                "400" => "#ffcc33",
                                "500" => "#ffc107",
                                "600" => "#cc9900",
                                "700" => "#997300",
                            ],
                            "success" => [
                                "50" => "#edf7ee",
                                "100" => "#dbf0dc",
                                "200" => "#b8e0b9",
                                "300" => "#94d196",
                                "400" => "#71c173",
                                "500" => "#4caf4f",
                                "600" => "#3e8e40",
                                "700" => "#2e6b30",
                            ],
                        ],
                        "semantic" => [
                            "text" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.700}",
                                "tertiary" => "{neutral.500}",
                                "disabled" => "{neutral.400}",
                                "inverse" => "{neutral.0}",
                                "link" => "{primary.600}",
                                "linkHover" => "{primary.700}",
                            ],
                            "background" => [
                                "page" => "{neutral.50}",
                                "section" => "{neutral.100}",
                                "card" => "{neutral.0}",
                                "overlay" => "rgba(0,0,0,0.4)",
                            ],
                            "border" => [
                                "default" => "{neutral.200}",
                                "strong" => "{neutral.300}",
                                "inverse" => "{neutral.0}",
                            ],
                            "icon" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.600}",
                                "tertiary" => "{neutral.500}",
                                "inverse" => "{neutral.0}",
                                "brand" => "{primary.500}",
                            ],
                            "button" => [
                                "primary" => [
                                    "bg" => "{primary.500}",
                                    "bgHover" => "{primary.600}",
                                    "bgPressed" => "{primary.700}",
                                    "bgDisabled" => "{primary.300}",
                                    "text" => "{neutral.0}",
                                ],
                                "secondary" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{primary.50}",
                                    "bgPressed" => "{primary.100}",
                                    "text" => "{primary.600}",
                                    "textDisabled" => "{primary.300}",
                                    "border" => "{primary.500}",
                                ],
                                "ghost" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{neutral.900}",
                                ],
                            ],
                            "status" => [
                                "error" => [
                                    "main" => "{error.500}",
                                    "bg" => "{error.50}",
                                    "text" => "{error.700}",
                                ],
                                "warning" => [
                                    "main" => "{warning.500}",
                                    "bg" => "{warning.50}",
                                    "text" => "{warning.700}",
                                ],
                                "success" => [
                                    "main" => "{success.500}",
                                    "bg" => "{success.50}",
                                    "text" => "{success.700}",
                                ],
                            ],
                        ],
                    ],
                    "dark" => [
                        "primitive" => [
                            "primary" => [
                                "500" => "#42a542",
                                "600" => "#70b670",
                                "700" => "#9aca9a",
                            ],
                            "secondary" => [
                                "500" => "#e4be44",
                            ],
                            "neutral" => [
                                "0" => "#0d0d0d",
                                "50" => "#1a1a1a",
                                "100" => "#262626",
                                "200" => "#333333",
                                "300" => "#404040",
                                "400" => "#666666",
                                "500" => "#999999",
                                "600" => "#bfbfbf",
                                "700" => "#d9d9d9",
                                "800" => "#f2f2f2",
                                "900" => "#ffffff",
                            ],
                            "error" => [
                                "500" => "#ff6666",
                                "700" => "#ff9999",
                                "50" => "#330000",
                            ],
                            "warning" => [
                                "500" => "#ffd966",
                                "700" => "#ffe699",
                                "50" => "#332600",
                            ],
                            "success" => [
                                "500" => "#71c173",
                                "700" => "#94d196",
                                "50" => "#0f2410",
                            ],
                        ],
                        "semantic" => [
                            "text" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.700}",
                                "tertiary" => "{neutral.500}",
                                "disabled" => "{neutral.400}",
                                "inverse" => "{neutral.0}",
                                "link" => "{primary.600}",
                                "linkHover" => "{primary.700}",
                            ],
                            "background" => [
                                "page" => "{neutral.0}",
                                "section" => "{neutral.50}",
                                "card" => "{neutral.100}",
                                "overlay" => "rgba(0,0,0,0.6)",
                            ],
                            "border" => [
                                "default" => "{neutral.200}",
                                "strong" => "{neutral.300}",
                                "inverse" => "{neutral.0}",
                            ],
                            "icon" => [
                                "primary" => "{neutral.900}",
                                "secondary" => "{neutral.600}",
                                "tertiary" => "{neutral.500}",
                                "inverse" => "{neutral.0}",
                                "brand" => "{primary.500}",
                            ],
                            "button" => [
                                "primary" => [
                                    "bg" => "{primary.500}",
                                    "bgHover" => "{primary.600}",
                                    "bgPressed" => "{primary.700}",
                                    "bgDisabled" => "{primary.300}",
                                    "text" => "{neutral.0}",
                                ],
                                "secondary" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{primary.600}",
                                    "textDisabled" => "{primary.300}",
                                    "border" => "{primary.500}",
                                ],
                                "ghost" => [
                                    "bg" => "transparent",
                                    "bgHover" => "{neutral.100}",
                                    "bgPressed" => "{neutral.200}",
                                    "text" => "{neutral.900}",
                                ],
                            ],
                            "status" => [
                                "error" => [
                                    "main" => "{error.500}",
                                    "bg" => "{error.50}",
                                    "text" => "{error.700}",
                                ],
                                "warning" => [
                                    "main" => "{warning.500}",
                                    "bg" => "{warning.50}",
                                    "text" => "{warning.700}",
                                ],
                                "success" => [
                                    "main" => "{success.500}",
                                    "bg" => "{success.50}",
                                    "text" => "{success.700}",
                                ],
                            ],
                        ],
                    ],
                ]),
            ],
        ];

        Theme::insert($themes);
    }
}
